# Generated by Django 5.0.6 on 2024-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='media',
            field=models.ImageField(null=True, upload_to='book/'),
        ),
    ]
