# Generated by Django 5.0.6 on 2024-07-04 12:47

import book.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='media',
            field=models.ImageField(null=True, upload_to=book.helpers.SaveMedia.save_book_image_path),
        ),
    ]
