# Generated by Django 5.0.6 on 2024-07-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='media',
            new_name='image',
        ),
    ]
