# Generated by Django 5.0.7 on 2024-07-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_media_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='authors',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
