# Generated by Django 5.0.7 on 2024-07-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_book_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
